@startuml
'https://plantuml.com/class-diagram

interface Handler{
    +handleRequest(I input, Context context)
}

class AddSongToPlaylistActivity {
-Logger log
-PlaylistDao playlistDao
-AlbumTrackDao albumTrackDao
}


class CreatePlaylistActivity {
-Logger log
-PlaylistDao playlistDao
}

class GetPlaylistActivity {
-Logger log
-PlaylistDao playlistDao
}

class GetPlaylistSongsActivity {
-Logger log
-PlaylistDao playlistDao
}


class UpdatePlaylistActivity {
-Logger log
-PlaylistDao playlistDao
}

class AlbumTrackDao {
-DynamoDBMapper dynamoDbMapper
}

class PlaylistDao {
-DynamoDBMapper dynamoDbMapper
+Playlist getPlaylist(String id)
}

class AlbumTrack {
@DynamoDBHashKey asin: String
@DynamoDBRangeKey trackNumber : Integer
albumName : String
songTitle: String
}

class Playlist {
@DynamoDBHashKey id: String
name : String
customerId: String
}

class AlbumTrackNotFoundException {
-DynamoDBMapper dynamoDbMapper
+Playlist getPlaylist(String id)
}









Handler <|.. AddSongToPlaylistActivity
Handler <|.. CreatePlaylistActivity
Handler <|.. GetPlaylistActivity
Handler <|.. GetPlaylistSongsActivity
Handler <|.. UpdatePlaylistActivity




@enduml